sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=django111
  - DJANGO=django20
  - DJANGO=djangomaster

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=django20
    - python: "2.7"
      env: DJANGO=djangomaster
  allow_failures:
    - env: DJANGO=djangomaster

before_install:
  - pip install codecov

install:
  - pip install tox

script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

after_success:
  - codecov
